version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py
