###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder, ClassPropertyViewer, EnumValueViewer
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["Invoices","Products",]
        ), enums=set(
          []
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)


    @property
    def Invoices(self) -> "InvoicesAst":
        return InvoicesAst(self)

    @property
    def Products(self) -> "ProductsAst":
        return ProductsAst(self)





class InvoicesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Invoices")
        self._properties: typing.Set[str] = set([ "datetime",  "products",  "total", ])
        self._props = InvoicesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "InvoicesProperties":
        return self._props


class InvoicesViewer(InvoicesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class InvoicesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def datetime(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("datetime"))

    @property
    def products(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("products"))

    @property
    def total(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("total"))

    

class ProductsAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Products")
        self._properties: typing.Set[str] = set([ "product_name",  "product_quantity",  "product_unit_price",  "product_price", ])
        self._props = ProductsProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ProductsProperties":
        return self._props


class ProductsViewer(ProductsAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ProductsProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def product_name(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("product_name"))

    @property
    def product_quantity(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("product_quantity"))

    @property
    def product_unit_price(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("product_unit_price"))

    @property
    def product_price(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("product_price"))

    




__all__ = ["TypeBuilder"]